packages:
  # pacemaker: 2.1.2-1ubuntu3.1
  # corosync: 3.1.6-1ubuntu1
  # crmsh: 4.3.1-1ubuntu3
  # pacemaker-resource-agents: 2.1.2-1ubuntu3.1
  # resource-agents: 1:4.7.0-1ubuntu7.2
  pacemaker: 
  corosync:
  crmsh: 
  pacemaker-resource-agents: 
  resource-agents: 
nmcli:
  # nmcli: 1.36.6-0ubuntu2
  nmcli:
targetcli:
  # targetcli: 1:2.1.53-1ubuntu3
  targetcli: